server:
  port: 9000

spring:
  application:
    name: auction-apiGateway-server
  cloud:
    gateway:
      routes:

        - id: member-service-server
          uri: http://127.0.0.1:7070
          predicates:
            - Path=/members/**

        - id: auction-service-server
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/auctions/**

        - id: receipt-service-server
          uri: http://127.0.0.1:9090
          predicates:
            - Path=/receipts/**
logging:
  level:
    io.netty: DEBUG
