server:
  port: 9000

spring:
  application:
    name: auction-apiGateway-server
  cloud:
    gateway:
      routes:

        - id: member-service-server
          uri: http://localhost:7070
          predicates:
            - Path=/auth/**

        - id: auction-service-server
          uri: http://localhost:8080
          predicates:
            - Path=/auction/**

        - id: receipt-service-server
          uri: http://localhost:9090
          predicates:
            - Path=/receipt/**
